# This is a basic workflow to help you get started with Actions
name: sample_worflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called " sample_job "
  sample_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runner's shell
      - name: first_step
        run: echo "this is the first step"
      # Runs a set of commands using the runner's shell
      - name: second_step
        run: |
          echo "this is the second step"
          echo $PWD
